// Hidden, read-only admin dashboard. Two tabs:
//   BALANCE   — reads public/balance-report.json (generated by `npm run balance`)
//   TELEMETRY — queries Firestore telemetry to visualize real player data
// Gated by src/game/admin.ts. Professional, dark, consistent with the game aesthetic.

import { Fragment, useEffect, useMemo, useState } from 'react';
import './App.css';
import { ALL_MAPS, DIFFICULTIES } from './game/maps';
import { TOWERS, TOWER_MAP } from './game/towers';
import { clearAdmin } from './game/admin';
import { fetchTelemetry, type TelemetryRow } from './game/leaderboard';

// ---- report shape (mirrors scripts/balance.ts) ----

interface CurvePoint {
  wave: number; reached: number; leakPct: number; pressure: number;
  livesLost: number; coreFraction: number; creditsStart: number; towersStart: number;
}
interface WaveCurve { map: string; diff: string; skill: string; winRate: number; avgFinalWave: number; points: CurvePoint[] }
interface GridCell { map: string; diff: string; skill: string; avgWave: number; winRate: number; avgLives: number }
interface BuildPoint {
  label: string; tierA: number; tierB: number; cost: number; single: number; aoe: number; burn: number;
  dpsPerCredit: number; aoePerCredit: number; vsArmored: number; vsExplosiveImmune: number;
  vsCryoImmune: number; vsCloaked: number; vsBoss: number; utility: string[];
}
interface UpgradeStep {
  track: number; trackName: string; tier: number; name: string; desc: string; cost: number;
  deltaSingle: number; deltaAoe: number; valuePerCredit: number; flag: 'dead' | 'weak' | 'ok' | 'strong' | 'op';
}
interface TowerEfficiency {
  id: string; name: string; style: string; damageType: string; cost: number; unlockAt: number;
  builds: BuildPoint[]; steps: UpgradeStep[]; rawDpsT4: number; dpsPerCreditT4: number;
}
interface StrategyResult { name: string; desc: string; map: string; diff: string; avgWave: number; bestWave: number; winRate: number; avgLives: number }
interface SoloResult { id: string; name: string; cost: number; avgWave: number; bestWave: number; winRate: number }
interface Report {
  generatedAt: string;
  meta: { quick: boolean; curveSeeds: number; gridSeeds: number; stratSeeds: number; soloSeeds: number;
    strategyArena: { map: string; diff: string }; soloArena: { map: string; diff: string }; medianDpsPerCredit: number };
  curves: WaveCurve[]; grid: GridCell[]; efficiency: TowerEfficiency[]; strategies: StrategyResult[]; solo: SoloResult[];
}

const mapName = (id: string) => ALL_MAPS.find((m) => m.id === id)?.name ?? id;
const diffName = (id: string) => DIFFICULTIES.find((d) => d.id === id)?.name ?? id;
const towerGlow = (id: string) => TOWER_MAP[id]?.glow ?? '#4bcffa';

function winColor(w: number): string {
  if (w >= 1) return '#2ed573';
  if (w >= 0.5) return '#feca57';
  if (w > 0) return '#ff9f43';
  return '#ff4757';
}

// ---------------- tiny SVG charts ----------------

function HBars({ data, max, fmt, unit }: {
  data: { label: string; value: number; color: string; sub?: string }[]; max?: number; fmt?: (v: number) => string; unit?: string;
}) {
  const top = max ?? Math.max(1, ...data.map((d) => d.value));
  return (
    <div className="adm-bars">
      {data.map((d, i) => (
        <div key={i} className="adm-bar-row">
          <span className="adm-bar-label" title={d.label}>{d.label}</span>
          <div className="adm-bar-track">
            <div className="adm-bar-fill" style={{ width: `${(d.value / top) * 100}%`, background: d.color }} />
            <span className="adm-bar-val">{(fmt ? fmt(d.value) : d.value)}{unit ?? ''}{d.sub ? <span className="adm-bar-sub"> {d.sub}</span> : null}</span>
          </div>
        </div>
      ))}
    </div>
  );
}

/** Multi-series line chart over wave number (x). Series values are 0..1 fractions. */
function LineChart({ points, series, height = 200 }: {
  points: CurvePoint[];
  series: { key: keyof CurvePoint; label: string; color: string }[];
  height?: number;
}) {
  const W = 640, H = height, padL = 36, padB = 22, padT = 12, padR = 12;
  if (points.length === 0) return <div className="adm-empty">no waves recorded</div>;
  const xs = points.map((p) => p.wave);
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const sx = (w: number) => padL + ((w - minX) / Math.max(1, maxX - minX)) * (W - padL - padR);
  const sy = (v: number) => padT + (1 - Math.max(0, Math.min(1, v))) * (H - padT - padB);
  return (
    <svg className="adm-line" viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="xMidYMid meet">
      {[0, 0.25, 0.5, 0.75, 1].map((g) => (
        <g key={g}>
          <line x1={padL} y1={sy(g)} x2={W - padR} y2={sy(g)} className="adm-grid" />
          <text x={padL - 5} y={sy(g) + 3} className="adm-axis" textAnchor="end">{Math.round(g * 100)}</text>
        </g>
      ))}
      {[minX, Math.round((minX + maxX) / 2), maxX].map((w) => (
        <text key={w} x={sx(w)} y={H - 6} className="adm-axis" textAnchor="middle">w{w}</text>
      ))}
      {series.map((s) => {
        const d = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${sx(p.wave).toFixed(1)},${sy(p[s.key] as number).toFixed(1)}`).join(' ');
        return <path key={String(s.key)} d={d} fill="none" stroke={s.color} strokeWidth={2} />;
      })}
    </svg>
  );
}

// ---------------- BALANCE tab ----------------

function GridBlock({ grid, skill }: { grid: GridCell[]; skill: string }) {
  return (
    <div className="adm-grid-block">
      <div className="adm-grid-skill">{skill}</div>
      <table className="adm-table adm-wingrid">
        <thead>
          <tr><th>sector</th>{DIFFICULTIES.map((d) => <th key={d.id}>{d.name}</th>)}</tr>
        </thead>
        <tbody>
          {ALL_MAPS.map((m) => (
            <tr key={m.id}>
              <td className="adm-rowhead">{m.name}</td>
              {DIFFICULTIES.map((d) => {
                const c = grid.find((g) => g.map === m.id && g.diff === d.id && g.skill === skill);
                if (!c) return <td key={d.id}>—</td>;
                return (
                  <td key={d.id} style={{ color: winColor(c.winRate) }} title={`${Math.round(c.winRate * 100)}% win · avg ${c.avgLives} cores left`}>
                    w{Math.round(c.avgWave)} · {Math.round(c.winRate * 100)}%
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function CurveViewer({ curves }: { curves: WaveCurve[] }) {
  const [mapId, setMapId] = useState(curves[0]?.map ?? 'orbital');
  const [diffId, setDiffId] = useState(curves[0]?.diff ?? 'easy');
  const curve = curves.find((c) => c.map === mapId && c.diff === diffId);
  return (
    <div className="adm-card">
      <div className="adm-card-head">
        <h3>Per-wave balance curve</h3>
        <div className="adm-selects">
          <select value={mapId} onChange={(e) => setMapId(e.target.value)}>
            {ALL_MAPS.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}
          </select>
          <select value={diffId} onChange={(e) => setDiffId(e.target.value)}>
            {DIFFICULTIES.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
          </select>
        </div>
      </div>
      {curve ? (
        <>
          <div className="adm-curve-meta">
            bot: <b>{curve.skill}</b> · reaches wave <b>{Math.round(curve.avgFinalWave)}</b> ·{' '}
            <span style={{ color: winColor(curve.winRate) }}>{Math.round(curve.winRate * 100)}% win</span>
          </div>
          <LineChart
            points={curve.points}
            series={[
              { key: 'pressure', label: 'pressure', color: '#ff6b6b' },
              { key: 'leakPct', label: 'leak %', color: '#feca57' },
              { key: 'coreFraction', label: 'cores left', color: '#2ed573' },
            ]}
          />
          <div className="adm-legend">
            <span><i style={{ background: '#ff6b6b' }} /> pressure (cores lost this wave / cores at wave start)</span>
            <span><i style={{ background: '#feca57' }} /> leak % (fraction of the wave that broke through)</span>
            <span><i style={{ background: '#2ed573' }} /> cores remaining (fraction of starting pool)</span>
          </div>
          <p className="adm-hint">Spikes in the red line are difficulty walls; a falling green line that never recovers is a death spiral.</p>
        </>
      ) : <div className="adm-empty">No curve for this combination.</div>}
    </div>
  );
}

const FLAG_COLOR: Record<UpgradeStep['flag'], string> = {
  dead: '#ff4757', weak: '#ff9f43', ok: '#a4b0be', strong: '#54a0ff', op: '#2ed573',
};

function EfficiencyTable({ efficiency, median }: { efficiency: TowerEfficiency[]; median: number }) {
  const [open, setOpen] = useState<string | null>(null);
  const sorted = [...efficiency].sort((a, b) => b.dpsPerCreditT4 - a.dpsPerCreditT4);
  const valueOf = (t: TowerEfficiency): { label: string; color: string } => {
    if (t.style === 'support' || t.rawDpsT4 <= 0) return { label: 'utility', color: '#a4b0be' };
    if (t.dpsPerCreditT4 >= median * 1.4) return { label: 'over-valued', color: '#2ed573' };
    if (t.dpsPerCreditT4 <= median * 0.6) return { label: 'under-valued', color: '#ff9f43' };
    return { label: 'fair', color: '#a4b0be' };
  };
  return (
    <div className="adm-card">
      <div className="adm-card-head"><h3>Tower cost-efficiency</h3><span className="adm-hint">at A·t4 build · costMult 1 · click a row for upgrade-step breakdown</span></div>
      <table className="adm-table adm-eff">
        <thead>
          <tr>
            <th>tower</th><th>style</th><th>type</th><th>cost</th><th>raw DPS</th><th>DPS/⌬</th>
            <th title="effective vs Aegis armor">vs armor</th><th title="effective vs phase-cloak">vs cloak</th>
            <th title="effective vs boss hulls">vs boss</th><th>value</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((t) => {
            const b = t.builds[1];
            const v = valueOf(t);
            const isOpen = open === t.id;
            return (
              <Fragment key={t.id}>
                <tr className={`adm-eff-row ${isOpen ? 'open' : ''}`} onClick={() => setOpen(isOpen ? null : t.id)}>
                  <td><span className="adm-dot" style={{ background: towerGlow(t.id) }} />{t.name}</td>
                  <td className="adm-dim">{t.style}</td>
                  <td className="adm-dim">{t.damageType}</td>
                  <td>⌬{t.cost}</td>
                  <td>{t.rawDpsT4}</td>
                  <td>{b.dpsPerCredit.toFixed(3)}</td>
                  <td style={{ color: b.vsArmored === 0 ? '#ff4757' : undefined }}>{b.vsArmored}</td>
                  <td style={{ color: b.vsCloaked === 0 ? '#ff4757' : undefined }}>{b.vsCloaked}</td>
                  <td>{b.vsBoss}</td>
                  <td style={{ color: v.color }}>{v.label}</td>
                </tr>
                {isOpen && (
                  <tr className="adm-eff-detail">
                    <td colSpan={10}>
                      <div className="adm-steps">
                        {([0, 1] as const).map((tr) => (
                          <div key={tr} className="adm-steps-track">
                            <div className="adm-steps-name">{t.steps.find((s) => s.track === tr)?.trackName}</div>
                            {t.steps.filter((s) => s.track === tr).map((s) => (
                              <div key={s.tier} className="adm-step" title={s.desc}>
                                <span className="adm-step-flag" style={{ background: FLAG_COLOR[s.flag] }}>{s.flag}</span>
                                <span className="adm-step-name">t{s.tier} {s.name}</span>
                                <span className="adm-step-cost">⌬{s.cost}</span>
                                <span className="adm-step-d">+{s.deltaSingle}/{s.deltaAoe} dps</span>
                              </div>
                            ))}
                          </div>
                        ))}
                      </div>
                    </td>
                  </tr>
                )}
              </Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function BalanceTab({ report }: { report: Report }) {
  const skills = ['rookie', 'standard', 'expert'];
  const stratArena = `${mapName(report.meta.strategyArena.map)} · ${diffName(report.meta.strategyArena.diff)}`;
  const soloArena = `${mapName(report.meta.soloArena.map)} · ${diffName(report.meta.soloArena.diff)}`;
  return (
    <div className="adm-content">
      <div className="adm-meta-bar">
        Generated {new Date(report.generatedAt).toLocaleString()} ·{' '}
        {report.meta.quick ? 'QUICK pass' : 'full pass'} · curve seeds {report.meta.curveSeeds} · grid seeds {report.meta.gridSeeds}
      </div>

      <CurveViewer curves={report.curves} />

      <div className="adm-card">
        <div className="adm-card-head"><h3>Win grid</h3><span className="adm-hint">avg final wave · win rate, per bot skill</span></div>
        <div className="adm-grids">
          {skills.map((s) => <GridBlock key={s} grid={report.grid} skill={s} />)}
        </div>
      </div>

      <EfficiencyTable efficiency={report.efficiency} median={report.meta.medianDpsPerCredit} />

      <div className="adm-card">
        <div className="adm-card-head"><h3>Strategy matrix</h3><span className="adm-hint">{stratArena} · constrained bots, identical cadence</span></div>
        <HBars
          data={[...report.strategies].sort((a, b) => b.avgWave - a.avgWave).map((s) => ({
            label: s.name, value: s.avgWave, color: winColor(s.winRate),
            sub: `${Math.round(s.winRate * 100)}% win`,
          }))}
          fmt={(v) => `w${Math.round(v)}`}
        />
        <p className="adm-hint">Green bars cleared the campaign; flat low bars couldn't afford their opening — focus strategies that skip the early game starve.</p>
      </div>

      <div className="adm-card">
        <div className="adm-card-head"><h3>Solo viability</h3><span className="adm-hint">{soloArena} · one tower kind, maxed</span></div>
        <HBars
          data={[...report.solo].sort((a, b) => b.avgWave - a.avgWave).map((s) => ({
            label: s.name, value: s.avgWave, color: s.winRate >= 1 ? '#2ed573' : towerGlow(s.id),
            sub: s.winRate >= 1 ? 'solo win' : '',
          }))}
          fmt={(v) => `w${Math.round(v)}`}
        />
      </div>
    </div>
  );
}

// ---------------- TELEMETRY tab ----------------

function bucket(wave: number): string {
  if (wave <= 0) return 'w0';
  const lo = Math.floor((wave - 1) / 5) * 5 + 1;
  return `w${lo}-${lo + 4}`;
}

function TelemetryTab() {
  const [rows, setRows] = useState<TelemetryRow[] | null>(null);
  const [err, setErr] = useState(false);

  useEffect(() => {
    let live = true;
    fetchTelemetry(1000).then((r) => { if (live) { setRows(r); } }).catch(() => { if (live) setErr(true); });
    return () => { live = false; };
  }, []);

  const stats = useMemo(() => {
    if (!rows || rows.length === 0) return null;
    const n = rows.length;
    const avg = (f: (r: TelemetryRow) => number) => rows.reduce((s, r) => s + f(r), 0) / n;
    // death/end histogram bucketed by wave, split by kind
    const buckets = new Map<string, { gameover: number; victory: number; armistice: number }>();
    for (const r of rows) {
      const b = bucket(r.wave);
      const e = buckets.get(b) ?? { gameover: 0, victory: 0, armistice: 0 };
      if (r.kind === 'victory') e.victory++;
      else if (r.kind === 'armistice') e.armistice++;
      else e.gameover++;
      buckets.set(b, e);
    }
    const histo = [...buckets.entries()].sort((a, b) => {
      const na = parseInt(a[0].slice(1)); const nb = parseInt(b[0].slice(1)); return na - nb;
    });
    // win-rate by map and diff
    const byMap = winRateBy(rows, (r) => r.map, ALL_MAPS.map((m) => m.id), mapName);
    const byDiff = winRateBy(rows, (r) => r.diff, DIFFICULTIES.map((d) => d.id), diffName);
    // tower popularity
    const towerCount = new Map<string, number>();
    let withTowers = 0;
    for (const r of rows) {
      if (r.towers) {
        withTowers++;
        for (const id of r.towers.split(',').filter(Boolean)) towerCount.set(id, (towerCount.get(id) ?? 0) + 1);
      }
    }
    const popularity = TOWERS.map((t) => ({ id: t.id, name: t.name, count: towerCount.get(t.id) ?? 0 }))
      .sort((a, b) => b.count - a.count);
    return {
      n, avgWave: avg((r) => r.wave), avgKills: avg((r) => r.kills), avgDur: avg((r) => r.durationS),
      wins: rows.filter((r) => r.won).length, histo, byMap, byDiff, popularity, withTowers,
    };
  }, [rows]);

  if (err) return <TelemetryError />;
  if (rows === null) return <div className="adm-content"><div className="adm-card"><div className="adm-empty">Establishing uplink to telemetry…</div></div></div>;
  if (rows.length === 0) return <TelemetryEmpty />;
  const s = stats!;
  const maxBucket = Math.max(1, ...s.histo.map(([, e]) => e.gameover + e.victory + e.armistice));

  return (
    <div className="adm-content">
      <div className="adm-meta-bar">{s.n} run events · {Math.round((s.wins / s.n) * 100)}% ended in a win</div>

      <div className="adm-stat-row">
        <Stat label="runs logged" value={s.n.toLocaleString()} />
        <Stat label="avg wave reached" value={s.avgWave.toFixed(1)} />
        <Stat label="avg hulls / run" value={Math.round(s.avgKills).toLocaleString()} />
        <Stat label="avg run length" value={`${Math.round(s.avgDur / 60)}m ${Math.round(s.avgDur % 60)}s`} />
      </div>

      <div className="adm-card">
        <div className="adm-card-head"><h3>Run outcome by wave reached</h3><span className="adm-hint">where players' runs end</span></div>
        <div className="adm-histo">
          {s.histo.map(([b, e]) => {
            const total = e.gameover + e.victory + e.armistice;
            return (
              <div key={b} className="adm-histo-col" title={`${b}: ${e.gameover} lost · ${e.victory} won · ${e.armistice} armistice`}>
                <div className="adm-histo-stack" style={{ height: `${(total / maxBucket) * 100}%` }}>
                  <div style={{ flex: e.gameover, background: '#ff4757' }} />
                  <div style={{ flex: e.victory, background: '#2ed573' }} />
                  <div style={{ flex: e.armistice, background: '#ffd32a' }} />
                </div>
                <span className="adm-histo-label">{b}</span>
              </div>
            );
          })}
        </div>
        <div className="adm-legend">
          <span><i style={{ background: '#ff4757' }} /> grid offline</span>
          <span><i style={{ background: '#2ed573' }} /> sector secured</span>
          <span><i style={{ background: '#ffd32a' }} /> armistice</span>
        </div>
      </div>

      <div className="adm-two">
        <div className="adm-card">
          <div className="adm-card-head"><h3>Win rate by sector</h3></div>
          <HBars data={s.byMap.map((d) => ({ label: d.label, value: Math.round(d.rate * 100), color: winColor(d.rate), sub: `${d.n} runs` }))} max={100} unit="%" />
        </div>
        <div className="adm-card">
          <div className="adm-card-head"><h3>Win rate by protocol</h3></div>
          <HBars data={s.byDiff.map((d) => ({ label: d.label, value: Math.round(d.rate * 100), color: winColor(d.rate), sub: `${d.n} runs` }))} max={100} unit="%" />
        </div>
      </div>

      <div className="adm-card">
        <div className="adm-card-head"><h3>Tower popularity</h3><span className="adm-hint">{s.withTowers} of {s.n} runs reported a loadout</span></div>
        {s.withTowers === 0
          ? <div className="adm-empty">No loadout data yet — runs logged before this build don't include tower composition. New runs will populate this.</div>
          : <HBars data={s.popularity.map((t) => ({ label: t.name, value: t.count, color: towerGlow(t.id) }))} />}
      </div>
    </div>
  );
}

function winRateBy(rows: TelemetryRow[], key: (r: TelemetryRow) => string, order: string[], label: (id: string) => string) {
  const m = new Map<string, { wins: number; n: number }>();
  for (const r of rows) {
    const k = key(r);
    const e = m.get(k) ?? { wins: 0, n: 0 };
    e.n++; if (r.won) e.wins++;
    m.set(k, e);
  }
  return order.filter((id) => m.has(id)).map((id) => {
    const e = m.get(id)!;
    return { id, label: label(id), rate: e.wins / e.n, n: e.n };
  });
}

function Stat({ label, value }: { label: string; value: string }) {
  return <div className="adm-stat"><div className="adm-stat-val">{value}</div><div className="adm-stat-label">{label}</div></div>;
}

function TelemetryEmpty() {
  return (
    <div className="adm-content"><div className="adm-card">
      <div className="adm-empty">
        <p>No telemetry returned.</p>
        <p className="adm-hint">Either no runs have been logged yet, or the telemetry collection is still read-blocked.
          The dashboard needs <code>allow read: if true</code> on <code>/telemetry</code> in firestore.rules (deploy required).</p>
      </div>
    </div></div>
  );
}

function TelemetryError() {
  return (
    <div className="adm-content"><div className="adm-card">
      <div className="adm-empty">
        <p>Telemetry read failed.</p>
        <p className="adm-hint">Firestore likely still denies reads on <code>/telemetry</code>. Deploy the updated firestore.rules
          (telemetry is read-enabled there) to populate this tab.</p>
      </div>
    </div></div>
  );
}

// ---------------- shell ----------------

export default function AdminDashboard() {
  const [tab, setTab] = useState<'balance' | 'telemetry'>('balance');
  const [report, setReport] = useState<Report | null | 'missing'>(null);

  useEffect(() => {
    fetch('/balance-report.json', { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((j: Report) => setReport(j))
      .catch(() => setReport('missing'));
  }, []);

  return (
    <div className="adm-root">
      <header className="adm-topbar">
        <div className="adm-brand">
          <span className="adm-eyebrow">LANTERN SEVEN · OPERATIONS</span>
          <h1>BALANCE &amp; TELEMETRY CONSOLE</h1>
        </div>
        <nav className="adm-tabs">
          <button className={tab === 'balance' ? 'on' : ''} onClick={() => setTab('balance')}>BALANCE</button>
          <button className={tab === 'telemetry' ? 'on' : ''} onClick={() => setTab('telemetry')}>TELEMETRY</button>
        </nav>
        <div className="adm-actions">
          <span className="adm-readonly">READ-ONLY</span>
          <button className="adm-exit" onClick={() => { clearAdmin(); location.href = location.pathname; }}>EXIT</button>
        </div>
      </header>

      {tab === 'balance' ? (
        report === null ? <div className="adm-content"><div className="adm-card"><div className="adm-empty">Loading balance report…</div></div></div>
          : report === 'missing'
            ? <div className="adm-content"><div className="adm-card"><div className="adm-empty">
                <p>No balance report found at <code>/balance-report.json</code>.</p>
                <p className="adm-hint">Run <code>npm run balance</code> to generate it.</p>
              </div></div></div>
            : <BalanceTab report={report} />
      ) : <TelemetryTab />}
    </div>
  );
}
